# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/tensorflow/tensorflow.git'


target 'StyleTransfer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StyleTransfer
  pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['Metal']
  # pod 'TensorFlowLiteSwift', '~> 2.11.0', :subspecs => ['Metal']
end
