# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/tensorflow/tensorflow.git'

target 'MUSIQ-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MUSIQ-Demo
  pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['Metal']
  pod 'TensorFlowLiteSelectTfOps', '~> 0.0.1-nightly'
  pod 'TensorFlowLiteTaskVision', '~> 0.4.3'
end
